spring:
  liquibase:
    change-log: classpath:liquibase.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/timetable
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true